# Pre-commit configuration for Django development
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks # Basic file quality checks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/psf/black # Code formatting
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13
        types: [python]
        # For Python files
        files: \.py$

  - repo: https://github.com/pycqa/isort # Import sorting
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        types: [python]

  - repo: https://github.com/astral-sh/ruff-pre-commit # Linting and additional formatting
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
        types: [python]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy # Static type checking
    rev: v1.18.1
    hooks:
      - id: mypy
        additional_dependencies:
          [django-stubs, djangorestframework-stubs, types-requests, types-redis]
        types: [python]

  - repo: https://github.com/PyCQA/bandit # Security scanning
    rev: 1.8.6
    hooks:
      - id: bandit
        name: bandit (python)
        description: Find common security issues
        entry: bandit -r .
        language: python
        language_version: python3
        types: [python]
        args: [-c, .bandit.yml]

  - repo: local # Django-specific checks and tests
    hooks:
      - id: django-check
        name: Django System Check
        entry: python manage.py check --deploy
        language: system
        pass_filenames: false

      - id: django-migrations
        name: Django Migration Check
        entry: python manage.py makemigrations --check --dry-run
        language: system
        pass_filenames: false

      - id: security-audit
        name: Security Audit
        entry: python -m safety scan --full-report
        language: system
        pass_filenames: false
